//
//  scripts/seed.mjs — the demo catalogue, seeded THROUGH the admin routes with the operator
//  identity (the same path the Manage View uses; nothing writes the database directly).
//  Content lives in `catalogue.mjs`; key art is generated by `gen-art.mjs`; media is a set
//  of Blender Foundation open-movie MP4s (CC-BY) standing in for episode streams. The
//  hosted lane swaps these for Stream HLS URLs.
//
//  IDEMPOTENT BY TITLE. `upsertShow` with no `id` always CREATES, so the first version of
//  this script duplicated the whole catalogue on every run — and a show added by hand from
//  the Manage screen (title only, no key art) stayed in the rails forever showing the "NO
//  KEY ART" placeholder. It now reads the existing rows first, matches on title, and passes
//  the id: run it as often as you like, and it converges the database onto the manifest.
//
import { readFileSync, existsSync } from "node:fs";
import { SHOWS, epTitle , metricsFor, tagsFor, flagsFor } from "./catalogue.mjs";

const BASE = process.env.BASE ?? "http://localhost:8787";
// The session moved out of `public/`: `despia build` copies that directory into `dist/`,
// which `despia deploy cloudflare` uploads, so the operator token was shipping with every
// deployment (scripts/dev-session.mjs's header has the whole story; scripts/dist-guard.mjs
// is the gate that now refuses it). It lives at the repo root, gitignored, read here off
// disk — the seeder is a local operator tool and never goes through the origin for it.
const SESSION_FILE = ".dev-session.json";
if (!existsSync(SESSION_FILE)) {
  console.error(`[seed] ${SESSION_FILE} is missing — run \`npm run session\` first.`);
  process.exit(1);
}
const session = JSON.parse(readFileSync(SESSION_FILE, "utf8"));
const OP = session.operator.token;

const call = async (path, body) => {
  const res = await fetch(`${BASE}${path}`, {
    method: "POST",
    headers: { authorization: `Bearer ${OP}`, "content-type": "application/json" },
    body: JSON.stringify(body),
  });
  const data = await res.json().catch(() => ({}));
  if (!res.ok) throw new Error(`${path} → ${res.status} ${JSON.stringify(data)}`);
  return data;
};

const CDN = "/media";

const existingShows = (await call("/internal/admin/listshows", {})).rows ?? [];
const showIdByTitle = new Map(existingShows.map((s) => [s.title, s.id]));
console.log(`[seed] ${existingShows.length} show(s) already present`);

let created = 0;
let updated = 0;
let episodesWritten = 0;

// COMING-SOON DATES ARE RELATIVE TO NOW (catalogue.mjs `releaseIn`): the seed writes the ISO
// timestamp, at 18:00 local on that day, so a countdown reads "in 3 days" the day it is seeded
// and the local notification has a real instant to fire at. Re-seeding moves the dates forward
// again — a demo whose premieres are all in the past is a demo of an empty rail.
const releaseAtFor = (days) => {
  const d = new Date();
  d.setDate(d.getDate() + days);
  d.setHours(18, 0, 0, 0);
  return d.toISOString();
};

for (const s of SHOWS) {
  const comingSoon = s.comingSoon === true;
  const values = {
    title: s.title,
    synopsis: s.synopsis,
    genre: s.genre,
    poster: `/posters/${s.slug}-poster.svg`,
    // the 2:3 art the reference home is built on, and the show's title art for the player's
    // episodes sheet — both generated by gen-art.mjs beside the 3:4 poster and the two heroes
    cover: `/posters/${s.slug}-cover.svg`,
    titleArt: `/posters/${s.slug}-title.svg`,
    hero: `/posters/${s.slug}-hero.svg`,
    heroTall: `/posters/${s.slug}-hero-tall.svg`,
    state: "live",
    freeUntil: s.freeUntil,
    featured: s.featured,
    ...metricsFor(s.slug),
    tags: tagsFor(s.slug),
    ...flagsFor(s.slug),
    comingSoon,
    // only a coming-soon show carries a date; the key is OMITTED otherwise (never `null` —
    // the admin action passes values straight to data.create, AGENTS.md)
    ...(comingSoon ? { releaseAt: releaseAtFor(s.releaseIn ?? 7) } : {}),
  };
  const known = showIdByTitle.get(s.title);
  const show = await call("/internal/admin/upsertshow", known ? { ...values, id: known } : values);
  const showId = show.id;
  if (known) updated += 1; else created += 1;

  // episodes are keyed by (show, idx) the same way — an existing row is updated in place so
  // a re-seed after changing a price does not leave two EP 4s behind
  const have = (await call("/internal/admin/listepisodes", { show: showId })).rows ?? [];
  const epIdByIdx = new Map(have.map((e) => [e.idx, e.id]));

  for (let i = 1; i <= s.episodes; i++) {
    const ep = {
      show: showId,
      idx: i,
      title: epTitle(i),
      // THE HLS MASTER, never the flat MP4: the player's Subtitles and Quality sheets render
      // the tracks and the rendition ladder the STREAM carries (`<video tracks=/variants=>`),
      // and only HLS carries both on every lane. scripts/gen-hls.mjs writes the ladder
      // (360p · 240p · 144p, honest to the 360p demo masters) and ten WebVTT renditions
      // beside each source clip; the origin gates the whole directory as one episode and
      // tokenizes every playlist it serves (scripts/serve.mjs tokenizedPlaylist).
      videoUrl: `${CDN}/${s.media}/master.m3u8`,
      poster: `/posters/${s.slug}-poster.svg`,
      duration: 60 + ((i * 7) % 45), // 60–104s: a vertical drama episode, varied per index
      price: s.price,
      // a coming-soon show's episodes are DRAFTS: real rows nobody can watch yet, so the
      // premiere is one `publish` flip per episode rather than a second seed
      state: comingSoon ? "draft" : "live",
    };
    const knownEp = epIdByIdx.get(i);
    await call("/internal/admin/upsertepisode", knownEp ? { ...ep, id: knownEp } : ep);
    episodesWritten += 1;
  }
  console.log(`[seed] ${known ? "updated" : "created"} ${s.title} — ${s.episodes} episodes${comingSoon ? ` (coming soon · ${values.releaseAt})` : ""}`);
}

// Anything in the database that the manifest does not name is demo debris (a show added by
// hand while testing the Manage screen). It cannot be deleted through the admin surface —
// there is no destructive route by design — so it is UNPUBLISHED, which takes it out of
// every public read while leaving the row recoverable from the Manage screen.
const manifestTitles = new Set(SHOWS.map((s) => s.title));
let retired = 0;
for (const row of existingShows) {
  if (manifestTitles.has(row.title)) continue;
  if (row.state !== "live") continue;
  await call("/internal/admin/publish", { show: row.id, state: "draft" });
  console.log(`[seed] retired "${row.title}" (not in the manifest) → draft`);
  retired += 1;
}

const stats = await call("/internal/admin/stats", {});
console.log(
  `[seed] ${created} created · ${updated} updated · ${retired} retired · ${episodesWritten} episode rows`,
);
console.log("[seed] stats:", JSON.stringify(stats));
