//
//  scripts/seed.mjs — the demo catalogue, seeded THROUGH the admin routes with the operator
//  identity (the same path the Manage View uses; nothing writes the database directly).
//  Content lives in `catalogue.mjs`; key art is generated by `gen-art.mjs`; media is a set
//  of Blender Foundation open-movie MP4s (CC-BY) standing in for episode streams. The
//  hosted lane swaps these for Stream HLS URLs.
//
//  IDEMPOTENT BY TITLE. `upsertShow` with no `id` always CREATES, so the first version of
//  this script duplicated the whole catalogue on every run — and a show added by hand from
//  the Manage screen (title only, no key art) stayed in the rails forever showing the "NO
//  KEY ART" placeholder. It now reads the existing rows first, matches on title, and passes
//  the id: run it as often as you like, and it converges the database onto the manifest.
//
import { readFileSync } from "node:fs";
import { SHOWS, epTitle , metricsFor, tagsFor } from "./catalogue.mjs";

const BASE = process.env.BASE ?? "http://localhost:8787";
const session = JSON.parse(readFileSync("public/dev-session.json", "utf8"));
const OP = session.operator.token;

const call = async (path, body) => {
  const res = await fetch(`${BASE}${path}`, {
    method: "POST",
    headers: { authorization: `Bearer ${OP}`, "content-type": "application/json" },
    body: JSON.stringify(body),
  });
  const data = await res.json().catch(() => ({}));
  if (!res.ok) throw new Error(`${path} → ${res.status} ${JSON.stringify(data)}`);
  return data;
};

const CDN = "/media";

const existingShows = (await call("/internal/admin/listshows", {})).rows ?? [];
const showIdByTitle = new Map(existingShows.map((s) => [s.title, s.id]));
console.log(`[seed] ${existingShows.length} show(s) already present`);

let created = 0;
let updated = 0;
let episodesWritten = 0;

for (const s of SHOWS) {
  const values = {
    title: s.title,
    synopsis: s.synopsis,
    genre: s.genre,
    poster: `/posters/${s.slug}-poster.svg`,
    hero: `/posters/${s.slug}-hero.svg`,
    heroTall: `/posters/${s.slug}-hero-tall.svg`,
    state: "live",
    freeUntil: s.freeUntil,
    featured: s.featured,
    ...metricsFor(s.slug),
    tags: tagsFor(s.slug),
  };
  const known = showIdByTitle.get(s.title);
  const show = await call("/internal/admin/upsertshow", known ? { ...values, id: known } : values);
  const showId = show.id;
  if (known) updated += 1; else created += 1;

  // episodes are keyed by (show, idx) the same way — an existing row is updated in place so
  // a re-seed after changing a price does not leave two EP 4s behind
  const have = (await call("/internal/admin/listepisodes", { show: showId })).rows ?? [];
  const epIdByIdx = new Map(have.map((e) => [e.idx, e.id]));

  for (let i = 1; i <= s.episodes; i++) {
    const ep = {
      show: showId,
      idx: i,
      title: epTitle(i),
      videoUrl: `${CDN}/${s.media}.mp4`,
      poster: `/posters/${s.slug}-poster.svg`,
      duration: 60 + ((i * 7) % 45), // 60–104s: a vertical drama episode, varied per index
      price: s.price,
      state: "live",
    };
    const knownEp = epIdByIdx.get(i);
    await call("/internal/admin/upsertepisode", knownEp ? { ...ep, id: knownEp } : ep);
    episodesWritten += 1;
  }
  console.log(`[seed] ${known ? "updated" : "created"} ${s.title} — ${s.episodes} episodes`);
}

// Anything in the database that the manifest does not name is demo debris (a show added by
// hand while testing the Manage screen). It cannot be deleted through the admin surface —
// there is no destructive route by design — so it is UNPUBLISHED, which takes it out of
// every public read while leaving the row recoverable from the Manage screen.
const manifestTitles = new Set(SHOWS.map((s) => s.title));
let retired = 0;
for (const row of existingShows) {
  if (manifestTitles.has(row.title)) continue;
  if (row.state !== "live") continue;
  await call("/internal/admin/publish", { show: row.id, state: "draft" });
  console.log(`[seed] retired "${row.title}" (not in the manifest) → draft`);
  retired += 1;
}

const stats = await call("/internal/admin/stats", {});
console.log(
  `[seed] ${created} created · ${updated} updated · ${retired} retired · ${episodesWritten} episode rows`,
);
console.log("[seed] stats:", JSON.stringify(stats));
